services:
  offlinepos:
    build: .
    ports:
      - "5000:5000"  # Flask backend
      - "8000:8000"  # Flet frontend (web)
    volumes:
      - ./offline_pos.db:/app/offline_pos.db
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - FLET_HOST=0.0.0.0
    dns:
      - 8.8.8.8
      - 8.8.4.4
