

services:
  offlinepos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./offline_pos.db:/app/offline_pos.db
    networks:
      - offlinepos-network

networks:
  offlinepos-network:
    driver: bridge
